"use client";
import React from "react";
import { fadeInUp } from "@/utils/animations";
import { motion } from "framer-motion";

const StandartsLoop = () => {
  return (
    <section className="standarts-loop">
      <img src="/images/home/ellipse2.png" />
      <img src="/images/home/ellipse3.png" />
      <div className="_container">
        <div className="standarts-loop__body">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeInUp}
            className="title"
          >
            <h2>Privacy Standards</h2>
            <p>
              We take privacy seriously and follow strict guidelines to protect
              the data you entrust to us.
            </p>
          </motion.div>
          <div className="row">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>01</span>
              <h3>Secure Data Handling</h3>
              <p>
                All information uploaded to our system is encrypted and stored
                securely to prevent unauthorized access.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>02</span>
              <h3>Restricted Usage</h3>
              <p>
                Your data is used exclusively for delivering the agreed services
                and is never shared with third parties without your explicit
                consent.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>03</span>
              <h3>Compliance</h3>
              <p>
                We adhere to global privacy regulations to ensure your business
                remains compliant at all times.
              </p>
            </motion.div>
          </div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeInUp}
            className="title"
          >
            <h2>Business Ethics</h2>
            <p>
              Our approach to business is grounded in integrity and
              transparency:
            </p>
          </motion.div>
          <div className="row">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>01</span>
              <h3>Fair Practices</h3>
              <p>
                We believe in honesty, fairness, and building trust in every
                interaction with our clients.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>02</span>
              <h3>Accountability</h3>
              <p>
                We take responsibility for delivering high-quality services and
                maintaining open communication.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>03</span>
              <h3>Customer-Centric Approach</h3>
              <p>
                Approach: Your success is our priority, and we design our
                solutions to align with your business goals.
              </p>
            </motion.div>
          </div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeInUp}
            className="title"
          >
            <h2>Handling Customer Data</h2>
            <p>
              We ensure that all data provided by your business and <br />
              the results generated by Airis are treated with care and <br />
              respect.
            </p>
          </motion.div>
          <div className="row">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>01</span>
              <h3>Ownership</h3>
              <p>
                The data you provide and the insights generated by Airis remain
                your property.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>02</span>
              <h3>Confidentiality</h3>
              <p>
                We protect the confidentiality of your business data and ensure
                it is used solely for your benefit.
              </p>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              className="item"
            >
              <span>03</span>
              <h3>Transparency</h3>
              <p>
                Reports and insights are presented in a clear and actionable
                format, giving you complete visibility and control over your
                information.
              </p>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StandartsLoop;
